[package]
name = "time_counter"
version = "0.1.0"
authors = ["Emmanuel Antony <emmanuelantony2000@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
valerie = { path = "../../../valerie" }
wasm-timer = "0.2.4"

[profile.release]
lto = true
opt-level = 3
