[package]
name = "valerie"
version = "0.1.0"
authors = ["Emmanuel Antony <emmanuelantony2000@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
wasm-bindgen-futures = "0.4.13"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5" }
futures-intrusive = "0.3.1"
parking_lot = "0.10.2"
crossbeam = "0.7.3"
intrusive-collections = "0.9.0"

[dependencies.web-sys]
version = "0.3.40"
features = [
    "Window",
    "Document",
    "Node",
    "Element",
    "HtmlElement",
    "Text",
    "HtmlCollection",
]

[dev-dependencies]
wasm-bindgen = "0.2.63"
wasm-bindgen-test = "0.3.13"
